global.MilesTicketEventMethods = MilesTicketEventMethods
global.addRecipes = addRecipes
global.tooltipHandler = tooltipHandler
global.inventoryChangedHandler = inventoryChangedHandler
global.itemRightClickedHandler = itemRightClickedHandler
global.serverLoadedHandler = serverLoadedHandler
global.entityInteractedHandler = entityInteractedHandler